#include "stdafx.h"
#include "domainconstants.h"
///////////////////////////////////////
namespace geninfo {
	/////////////////////////////////////////////
	const string DomainConstants::TYPE("type");
	const string DomainConstants::ID("_id");
	const string DomainConstants::REV("_rev");
	const string DomainConstants::DELETED("_deleted");
	const string DomainConstants::STATUS("status");
	const string DomainConstants::DESCRIPTION("description");
	///////////////////////////////////////////////////
	const string DomainConstants::SIGLE("sigle");
	const string DomainConstants::NAME("name");
	const string DomainConstants::ORDER("ordre");
	const string DomainConstants::GENRE("genre");
	const string DomainConstants::CHILDRENIDS("childrenids");
	const string DomainConstants::STARTDATE("startdate");
	const string DomainConstants::ENDDATE("enddate");
	const string DomainConstants::MODULE("module");
	const string DomainConstants::COEFFICIENT("coefficient");
	const string DomainConstants::ECS("ecs");
	const string DomainConstants::DEPARTEMENTID("departementid");
	const string DomainConstants::UNITEID("uniteid");
	const string DomainConstants::ANNEEID("anneeid");
	const string DomainConstants::MATIEREID("matiereid");
	const string DomainConstants::SEMESTREID("semestreid");
	const string DomainConstants::GROUPEID("groupeid");
	const string DomainConstants::ENSEIGNANTID("enseignantid");
	const string DomainConstants::ETUDIANTID("etudiantid");
	const string DomainConstants::ENSEIGNANTAFFECTATIONID("enseignantaffectationid");
	const string DomainConstants::ETUDIANTAFFECTATIONID("etudiantaffectationid");
	const string DomainConstants::GROUPEEVENTID("groupeeventid");
	const string DomainConstants::LOCATION("location");
	const string DomainConstants::STARTTIME("starttime");
	const string DomainConstants::ENDTIME("endtime");
	const string DomainConstants::MINNOTE("minnote");
	const string DomainConstants::MAXNOTE("maxnote");
	const string DomainConstants::NOTE("note");
	const string DomainConstants::USERNAME("username");
	const string DomainConstants::PASSWORD("password");
	const string DomainConstants::FIRSTNAME("firstname");
	const string DomainConstants::LASTNAME("lastname");
	const string DomainConstants::EMAIL("email");
	const string DomainConstants::PHONE("phone");
	const string DomainConstants::DOSSIER("dossier");
	const string DomainConstants::SEXE("sexe");
	const string DomainConstants::BIRTHDATE("birthdate");
	const string DomainConstants::VILLE("ville");
	const string DomainConstants::ETABLISSEMENT("etablissement");
	const string DomainConstants::SERIEBAC("seriebac");
	const string DomainConstants::OPTIONBAC("optionbac");
	const string DomainConstants::MENTIONBAC("mentionbac");
	const string DomainConstants::ETUDESSUPERIEURES("etudessuperieures");
	const string DomainConstants::APB("apb");
	const string DomainConstants::REDOUBLANT("redoublant");
	//
	const string DomainConstants::DEPARTEMENTSIDS("departementids");
	const string DomainConstants::UNITESIDS("unitesids");
	const string DomainConstants::ANNEESIDS("anneesids");
	const string DomainConstants::SEMESTRESIDS("semestresids");
	const string DomainConstants::MATIERESIDS("matieresids");
	const string DomainConstants::AFFECTATIONSIDS("affectationsids");
	const string DomainConstants::EVENTSIDS("eventsids");
	const string DomainConstants::ADMINISTRATORSIDS("administratorsids");
	const string DomainConstants::ENSEIGNANTSIDS("enseignantsids");
	const string DomainConstants::ETUDIANTSIDS("etudiantsids");
	const string DomainConstants::GROUPESIDS("groupesids");
	//
	const string DomainConstants::GENRE_PROMO("PROMO");
	const string DomainConstants::GENRE_TD("TD");
	const string DomainConstants::GENRE_TP("TP");
	const string DomainConstants::GENRE_PRATIQUE("PRATIQUE");
	const string DomainConstants::GENRE_THEORIE("THEORIE");
	const string DomainConstants::GENRE_ABSENCE("ABS");
	const string DomainConstants::GENRE_RETARD("RET");
	const string DomainConstants::GENRE_MISC("MISC");
	const string DomainConstants::GENRE_NOTE("NOTE");
	//
	const string DomainConstants::DEPARTEMENT_TYPE("departement");
	const string DomainConstants::GROUPE_TYPE("groupe");
	const string DomainConstants::UNITE_TYPE("unite");
	const string DomainConstants::MATIERE_TYPE("matiere");
	const string DomainConstants::ANNEE_TYPE("annee");
	const string DomainConstants::SEMESTRE_TYPE("semestre");
	const string DomainConstants::PERSON_TYPE("person");
	const string DomainConstants::ADMINISTRATORPERSON_TYPE("administratorperson");
	const string DomainConstants::ENSEIGNANTPERSON_TYPE("enseignantperson");
	const string DomainConstants::ETUDIANTPERSON_TYPE("etudiantperson");
	const string DomainConstants::ENSEIGNANTAFFECTATION_TYPE("enseignantaffectation");
	const string DomainConstants::ETUDIANTAFFECTATION_TYPE("etudiantaffectation");
	const string DomainConstants::GROUPEEVENT_TYPE("groupeevent");
	const string DomainConstants::ETUDIANTEVENT_TYPE("etudiantevent");
	const string DomainConstants::ETUDIANT_TYPE("etudiant");
	const string DomainConstants::ENSEIGNANT_TYPE("enseignant");
	const string DomainConstants::ADMINISTRATOR_TYPE("administrator");
	const string DomainConstants::SUPERPERSON_TYPE("superperson");
	//
	const string DomainConstants::ETUDIANTEVENT_PREFIX("TV");
	const string DomainConstants::GROUPEEVENT_PREFIX("GV");
	const string DomainConstants::ETUDIANTAFFECTATION_PREFIX("TA");
	const string DomainConstants::ENSEIGNANTAFFECTATION_PREFIX("EA");
	const string DomainConstants::PERSON_PREFIX("PS");
	const string DomainConstants::SEMESTRE_PREFIX("SM");
	const string DomainConstants::MATIERE_PREFIX("MT");
	const string DomainConstants::UNITE_PREFIX("UN");
	const string DomainConstants::GROUPE_PREFIX("GP");
	const string DomainConstants::ANNEE_PREFIX("AN");
	const string DomainConstants::DEPARTEMENT_PREFIX("DP");
	const string DomainConstants::ETUDIANT_PREFIX("ET");
	const string DomainConstants::ENSEIGNANT_PREFIX("EN");
	const string DomainConstants::ADMINISTRATOR_PREFIX("AD");
	///////////////////////////////////////////////////////
}// namespace geninfo
